name: Build and Publish Artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macos-15", "ubuntu-24.04", "windows-2025" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proxxyy-${{ matrix.os }}
          path: target/release/proxxyy*
          if-no-files-found: warn

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: proxxyy-${{ matrix.os }}
          pattern: proxxyy-*
          merge-multiple: true
      - run: ls -R proxxyy-${{ matrix.os }}
